### ISSUE TITLE
无法提取数字、英文字符

### ISSUE THREAD

**Issue by lemondreamtobe** [iplus26/font-spider-walker#1]
```
const collect = [
  '2019! 我的提取',
  '人无再少年',
  'here test if picks English letters',
  '！@#¥%……&*（）'
]
```
存在一个文件，专门放了我想提取的字体集合
但是无法提取数字 和英文字符 
请问有什么方法可以支持？
![image](https://user-images.githubusercontent.com/22766436/69710254-09e50200-113a-11ea-95ac-871aac2f8d03.png)

**Comment by lemondreamtobe** [comment]
给你提了个merage,  通过增加命令行参数类型+扩展正则
实现可支持多类型字符的检索

**Comment by iplus26** [comment]
抱歉没有及时回复，如果是个例的需求，我暂时不会把这个PR合进来。
这个小工具本身就很简单，如果有需求的话可以fork一份。
